{"name": "test_01_login[data0]", "status": "failed", "statusDetails": {"message": "AssertionError: assert '账号密码错误' == ''\n  + 账号密码错误", "trace": "self = <test221010.test.test_LoginApi.TestLogin object at 0x0000018CC6B4D820>\ndata = [{'api': '/sdkLogin/playerAccount', 'except_value': '0', 'password': '123456', 'token': 'eyJhbGciOiJIUzUxMiJ9.eyJnYW1l...I6ImF1dGhvcml6YXRpb24ifQ.QpJX0_WxHUrq2iG47Zs134jrvJnucFjXICOKAr2UoFfbNSSViWShdG2mRDIks9SJxGgmK3zmKsWva1jAmEWVtg', ...}]\n\n    @pytest.mark.parametrize('data', yaml.load_all(open(r'E:\\A_PythonProject\\TestProject\\test221010\\test\\yml\\login.yml','r',encoding='utf-8')))\n    @allure.story('密码正确，登录成功')\n    @allure.severity('critical')\n    def test_01_login(self,data):\n        #组装数据\n        #mylog.mylog.info('开始接口测试')\n        with allure.step(\"添加请求头\"):\n            header = {'User-Agent':\"Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1\"}\n        #发送请求\n        with allure.step(\"发送请求\"):\n            res = requests.post(url=self.configurl+data[0]['api'],json={\n                \"account\": data[0]['user'],\n                \"password\": data[0]['password'],\n                \"gameId\": self.gameId,\n                \"apothecary_inexcusable_willful\": None,\n                \"fast_shelve\": None,\n                \"rhyme_systolic\": None\n            },headers=header)\n        #print(res.status_code)\n        response =res.json()\n        print(response)\n        #print(res.raw)\n        #断言\n        with allure.step('断言'):\n>           assert response['msg'] == ''\nE           AssertionError: assert '账号密码错误' == ''\nE             + 账号密码错误\n\ntest_LoginApi.py:92: AssertionError"}, "steps": [{"name": "添加请求头", "status": "passed", "start": 1673489404184, "stop": 1673489404184}, {"name": "发送请求", "status": "passed", "start": 1673489404184, "stop": 1673489404495}, {"name": "断言", "status": "failed", "statusDetails": {"message": "AssertionError: assert '账号密码错误' == ''\n  + 账号密码错误\n", "trace": "  File \"E:\\A_PythonProject\\TestProject\\test221010\\test\\test_LoginApi.py\", line 92, in test_01_login\n    assert response['msg'] == ''\n"}, "start": 1673489404496, "stop": 1673489404503}], "parameters": [{"name": "data", "value": "[{'api': '/sdkLogin/playerAccount', 'password': '123456', 'user': 'FZSLc53ud9yu', 'token': 'eyJhbGciOiJIUzUxMiJ9.eyJnYW1lSWQiOjczLCJhY2NvdW50SWQiOiIxMWVkNjZmNGZlM2VkZjIxNTI1NDAwOWMyZjA5Yjc3MCIsImV4cGlyZVRpbWUiOjE2NjkzNTAxMzcsImdyYW50VHlwZSI6ImF1dGhvcml6YXRpb24ifQ.QpJX0_WxHUrq2iG47Zs134jrvJnucFjXICOKAr2UoFfbNSSViWShdG2mRDIks9SJxGgmK3zmKsWva1jAmEWVtg', 'except_value': '0'}]"}], "start": 1673489404184, "stop": 1673489404517, "uuid": "f93d5ae8-47be-4a20-9359-779981a9a3e8", "historyId": "e086b35d6f6988ff75f3ef69583f0749", "testCaseId": "5a7366d16f4e8a26d9852f6b1e8d28e4", "fullName": "test_LoginApi.TestLogin#test_01_login", "labels": [{"name": "feature", "value": "登录注册模块"}, {"name": "severity", "value": "critical"}, {"name": "story", "value": "密码正确，登录成功"}, {"name": "epic", "value": "X项目"}, {"name": "suite", "value": "test_LoginApi"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-8H78TQB"}, {"name": "thread", "value": "15168-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_LoginApi"}]}