{"name": "test_05_tourist_loginfail", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 < 0", "trace": "self = <test.test_LoginApi.TestLogin object at 0x0000023CBB7F0040>\n\n    @allure.story(\"游客登录失败\")\n    def test_05_tourist_loginfail(self):\n        #mylog.mylog.info('开始接口测试')\n>       assert 1 < 0\nE       assert 1 < 0\n\ntest221010\\test\\test_LoginApi.py:260: AssertionError"}, "start": 1670386579855, "stop": 1670386579855, "uuid": "3a14071a-6301-4560-9009-42ef2eacf588", "historyId": "dc6e531ed4e8ec85a0615feb04566212", "testCaseId": "43f72ad0630a6da62b0cb5c8fd8ee6d8", "fullName": "test221010.test.test_LoginApi.TestLogin#test_05_tourist_loginfail", "labels": [{"name": "feature", "value": "登录注册模块"}, {"name": "story", "value": "游客登录失败"}, {"name": "parentSuite", "value": "test221010.test"}, {"name": "suite", "value": "test_LoginApi"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-8H78TQB"}, {"name": "thread", "value": "9800-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test221010.test.test_LoginApi"}]}